wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      4: 3.7.9
      5: 0.10.30
      8:
      - 5
